<?php
namespace ResourceCatalog\Model;

interface IResourceCatalog extends IResourceCatalogTypeName, IResourceCatalogTypeIdentify, IResourceCatalogTypeEnName, IResourceCatalogTypeDoublePublicity, IResourceCatalogTypeRedBlackList, IResourceCatalogIsConfirm
{
    const TYPE = array(
        'NULL' => 0,
        'XBXZCF' => 1,
        'XBXZXK' => 2,
        'JGJCDXZJL' => 3,
        'SJJXMXX' => 4,
        'GGXYZHPJ' => 5,
        'XSPJXX' => 6,
        'SXBZXJGXX' => 7,
        'SXBZXRMD' => 8,
        'YSCRJZJJJZGRDXX' => 9,
        'JDCWFXX' => 10,
        'ZFCGDLJGXX' => 11,
        'SJQYJSZXRDXX' => 12, 
        'JSZGXX' => 13,
        'SJYXXS' => 14,
        'JYJGXINXI' => 15,
        'GRRYXXJYJ' => 16,
        'JGRYXXSJYJ' => 17,
        'SFJDJGCYRYZGXX' => 18,
        'SFJDJGDJXX' => 19,
        'GZJGJBXX' => 20,
        'GZYXX' => 21,
        'JCFLFWSXX' => 22,
        'JCFLFWGZZJBXX' => 23,
        'LSSWSXX' => 24,
        'LSZYZGZXX' => 25,
        'JGRYXXSSFJ' => 26,
        'ZYJNZSXX' => 27,
        'YLBXXX' => 28,
        'YZTQSBXXHMD' => 29,
        'SYBXXX' => 30,
        'SBQYXX' => 31,
        'GZRYXX' => 32,
        'YZTQNMGGZHMD' => 33,
        'QSLHXJJTJL' => 34,
        'SLYSXKZXX' => 35,
        'GRRYXXJTJ' => 36,
        'CPTGLSZXCPRZMD' => 37,
        'ESCJDPGJGHZZS' => 38,
        'SHZZNJXX' => 39,
        'GRRYXXMZJ' => 40,
        'MBFQYML' => 41,
        'SHTTDJXX' => 42,
        'YXZZDWJBGXX' => 43,
        'GRRYXXGDJ' => 44,
        'JGRYXXSWGXJ' => 45,
        'QYGSZXXX' => 46,
        'AJNSRXX' => 47,
        'ZDSSWFAJXX' => 48,
        'QYDSXZCFXX' => 49,
        'DTJXJGRXX' => 50,
        'TJDCDXML' => 51,
        'QIYEJBXX' => 52,
        'GTGSHXX' => 53,
        'CMQYSBXX' => 54,
        'YPLSQYXX' => 55,
        'JGRYXX' => 56,
        'SXQYHMD' => 57,
        'SPYPTSJBJLGR' => 58,
        'SPYPTSJBJLDW' => 59,
        'JXMPCPXX' => 60,
        'QYYCMLXX' => 61,
        'QYZXXX' => 62,
        'QYDXXX' => 63,
        'CCJCJGXX' => 64,
        'LSTDFWBA' => 65,
        'SYDWFRDJXX' => 66,
        'JXSZLJDW' => 67,
        'XZXKQYXX' => 68,
        'DZDAGZZDWGRBZJL' => 69,
        'YXQNZYZ' => 70,
        'QYYH' => 71,
        'QFGRYHXX' => 72,
        'QFQYYHXX' => 73,
        'DLYHSXHMDJG' => 74,
        'DLYHSXHMDZRR' => 75,
        'TEST' => 500
    );

    const USERGROUP_TYPE_RELATIONSHIP = array(
        IUserGroup::ID['NULL'] => array(
            self::TYPE['NULL'],
            self::TYPE['XBXZCF'],
            self::TYPE['XBXZXK'],
        ),
        IUserGroup::ID['QFGW'] => array(self::TYPE['JGJCDXZJL'], self::TYPE['TEST'], self::TYPE['SJJXMXX'], self::TYPE['GGXYZHPJ']),
        IUserGroup::ID['QWXCB'] => array(),
        IUserGroup::ID['AYQZZB'] => array(),
        IUserGroup::ID['QWZFW'] => array(),
        IUserGroup::ID['QRMFY'] => array(self::TYPE['XSPJXX'], self::TYPE['SXBZXJGXX'], self::TYPE['SXBZXRMD']),
        IUserGroup::ID['QJCY'] => array(),
        IUserGroup::ID['QGAFJ'] => array(self::TYPE['YSCRJZJJJZGRDXX'], self::TYPE['JDCWFXX']),
        IUserGroup::ID['QCZJ'] => array(self::TYPE['ZFCGDLJGXX']),
        IUserGroup::ID['QGXJ'] => array(self::TYPE['SJQYJSZXRDXX']),
        IUserGroup::ID['QJYJ'] => array(
            self::TYPE['JSZGXX'],
            self::TYPE['SJYXXS'],
            self::TYPE['JYJGXINXI'],
            self::TYPE['GRRYXXJYJ'],
            self::TYPE['JGRYXXSJYJ']
        ),
        IUserGroup::ID['QSFJ'] => array(
            self::TYPE['SFJDJGCYRYZGXX'],
            self::TYPE['SFJDJGDJXX'],
            self::TYPE['GZJGJBXX'],
            self::TYPE['GZYXX'],
            self::TYPE['JCFLFWSXX'],
            self::TYPE['JCFLFWGZZJBXX'],
            self::TYPE['LSSWSXX'],
            self::TYPE['LSZYZGZXX'],
            self::TYPE['JGRYXXSSFJ']
        ),  
        IUserGroup::ID['QRSJ'] => array(
            self::TYPE['ZYJNZSXX'],
            self::TYPE['YLBXXX'],
            self::TYPE['YZTQSBXXHMD'],
            self::TYPE['SYBXXX'],
            self::TYPE['SBQYXX'],
            self::TYPE['GZRYXX'],
            self::TYPE['YZTQNMGGZHMD']
        ),  
        IUserGroup::ID['QZJJ'] => array(),  
        IUserGroup::ID['QGSL'] => array(),  
        IUserGroup::ID['QGBDST'] => array(),
        IUserGroup::ID['QSLJ'] => array(),
        IUserGroup::ID['QLYJ'] => array(self::TYPE['QSLHXJJTJL']),
        IUserGroup::ID['QJTYSJ'] => array(self::TYPE['SLYSXKZXX'], self::TYPE['GRRYXXJTJ']),
        IUserGroup::ID['AYSTHJJ'] => array(self::TYPE['CPTGLSZXCPRZMD']),
        IUserGroup::ID['QSAWJ'] => array(self::TYPE['ESCJDPGJGHZZS']),
        IUserGroup::ID['QMZJ'] => array(
            self::TYPE['SHZZNJXX'],
            self::TYPE['GRRYXXMZJ'],
            self::TYPE['MBFQYML'],
            self::TYPE['SHTTDJXX']
        ),
        IUserGroup::ID['QNYNCJ'] => array(),
        IUserGroup::ID['QWGXLJ'] => array(
            self::TYPE['YXZZDWJBGXX'],
            self::TYPE['GRRYXXGDJ'],
            self::TYPE['JGRYXXSWGXJ']
        ),
        IUserGroup::ID['QWJW'] => array(),
        IUserGroup::ID['QSUWJ'] => array(self::TYPE['QYGSZXXX'], self::TYPE['AJNSRXX'], self::TYPE['ZDSSWFAJXX'], self::TYPE['QYDSXZCFXX']),
        IUserGroup::ID['QTJJ'] => array(self::TYPE['DTJXJGRXX'], self::TYPE['TJDCDXML']),
        IUserGroup::ID['QSCJDGLJ'] => array(
            self::TYPE['QIYEJBXX'],
            self::TYPE['GTGSHXX'],
            self::TYPE['CMQYSBXX'],
            self::TYPE['YPLSQYXX'],
            self::TYPE['JGRYXX'],
            self::TYPE['SXQYHMD'],
            self::TYPE['SPYPTSJBJLGR'],
            self::TYPE['SPYPTSJBJLDW'],
            self::TYPE['JXMPCPXX'],
            self::TYPE['QYYCMLXX'],
            self::TYPE['QYZXXX'],
            self::TYPE['QYDXXX'],
            self::TYPE['CCJCJGXX']
        ),
        IUserGroup::ID['QYJGLJ'] => array(),
        IUserGroup::ID['QZFJRB'] => array(),
        IUserGroup::ID['QZWJ'] => array(self::TYPE['LSTDFWBA']),
        IUserGroup::ID['QXXZX'] => array(),
        IUserGroup::ID['QBWB'] => array(self::TYPE['SYDWFRDJXX']),
        IUserGroup::ID['QKJJ'] => array(self::TYPE['JXSZLJDW']),
        IUserGroup::ID['QSJJ'] => array(),
        IUserGroup::ID['QCSGLJ'] => array(self::TYPE['XZXKQYXX']),
        IUserGroup::ID['QDAJ'] => array(self::TYPE['DZDAGZZDWGRBZJL']),
        IUserGroup::ID['QZGH'] => array(),
        IUserGroup::ID['TQW'] => array(self::TYPE['YXQNZYZ']),
        IUserGroup::ID['ZGRSAYZGS'] => array(),
        IUserGroup::ID['QGDFGS'] => array(
            self::TYPE['QYYH'],
            self::TYPE['QFGRYHXX'],
            self::TYPE['QFQYYHXX'],
            self::TYPE['DLYHSXHMDJG'],
            self::TYPE['DLYHSXHMDZRR'],
        ),
        IUserGroup::ID['RBCXAYZGS'] => array(),
        IUserGroup::ID['GKZ'] => array(),
        IUserGroup::ID['QSZ'] => array(),
        IUserGroup::ID['AYZ'] => array(),
        IUserGroup::ID['WPZ'] => array(),
        IUserGroup::ID['FHJ'] => array(),
        IUserGroup::ID['BYIJ'] => array(),
        IUserGroup::ID['HBJ'] => array(),
        IUserGroup::ID['DDJ'] => array(),
        IUserGroup::ID['DJJ'] => array(),
        IUserGroup::ID['BYAJ'] => array(),
        IUserGroup::ID['CJGWH'] => array(),
    );

    const STATUS_NORMAL = 0;

    const STATUS_DELETE = -2;
}
