<?php
namespace ResourceCatalog\Model;

interface IUserGroupIdentify
{
    const IDENTIFY = array(
        IUserGroup::ID['NULL'] => 'NULL',
        IUserGroup::ID['QFGW'] => 'QFGW',
        IUserGroup::ID['QWXCB'] => 'QWXCB',
        IUserGroup::ID['AYQZZB'] => 'AYQZZB',
        IUserGroup::ID['QWZFW'] => 'QWZFW',
        IUserGroup::ID['QRMFY'] => 'QRMFY',
        IUserGroup::ID['QJCY'] => 'QJCY',
        IUserGroup::ID['QGAFJ'] => 'QGAFJ',
        IUserGroup::ID['QCZJ'] => 'QCZJ',
        IUserGroup::ID['QGXJ'] => 'QGXJ',
        IUserGroup::ID['QJYJ'] => 'QJYJ',
        IUserGroup::ID['QSFJ'] => 'QSFJ',
        IUserGroup::ID['QRSJ'] => 'QRSJ',
        IUserGroup::ID['QZJJ'] => 'QZJJ',
        IUserGroup::ID['QGSL'] => 'QGSL',
        IUserGroup::ID['QGBDST'] => 'QGBDST',
        IUserGroup::ID['QSLJ'] => 'QSLJ',
        IUserGroup::ID['QLYJ'] => 'QLYJ',
        IUserGroup::ID['QJTYSJ'] => 'QJTYSJ',
        IUserGroup::ID['AYSTHJJ'] => 'AYSTHJJ',
        IUserGroup::ID['QSAWJ'] => 'QSAWJ',
        IUserGroup::ID['QMZJ'] => 'QMZJ',
        IUserGroup::ID['QNYNCJ'] => 'QNYNCJ',
        IUserGroup::ID['QWGXLJ'] => 'QWGXLJ',
        IUserGroup::ID['QWJW'] => 'QWJW',
        IUserGroup::ID['QSUWJ'] => 'QSUWJ',
        IUserGroup::ID['QTJJ'] => 'QTJJ',
        IUserGroup::ID['QSCJDGLJ'] => 'QSCJDGLJ',
        IUserGroup::ID['QYJGLJ'] => 'QYJGLJ',
        IUserGroup::ID['QZFJRB'] => 'QZFJRB',
        IUserGroup::ID['QZWJ'] => 'QZWJ',
        IUserGroup::ID['QXXZX'] => 'QXXZX',
        IUserGroup::ID['QBWB'] => 'QBWB',
        IUserGroup::ID['QKJJ'] => 'QKJJ',
        IUserGroup::ID['QSJJ'] => 'QSJJ',
        IUserGroup::ID['QCSGLJ'] => 'QCSGLJ',
        IUserGroup::ID['QDAJ'] => 'QDAJ',
        IUserGroup::ID['QZGH'] => 'QZGH',
        IUserGroup::ID['TQW'] => 'TQW',
        IUserGroup::ID['ZGRSAYZGS'] => 'ZGRSAYZGS',
        IUserGroup::ID['QGDFGS'] => 'QGDFGS',
        IUserGroup::ID['RBCXAYZGS'] => 'RBCXAYZGS',
        IUserGroup::ID['GKZ'] => 'GKZ',
        IUserGroup::ID['QSZ'] => 'QSZ',
        IUserGroup::ID['AYZ'] => 'AYZ',
        IUserGroup::ID['WPZ'] => 'WPZ',
        IUserGroup::ID['FHJ'] => 'FHJ',
        IUserGroup::ID['BYIJ'] => 'BYIJ',
        IUserGroup::ID['HBJ'] => 'HBJ',
        IUserGroup::ID['DDJ'] => 'DDJ',
        IUserGroup::ID['DJJ'] => 'DJJ',
        IUserGroup::ID['BYAJ'] => 'BYAJ',
        IUserGroup::ID['CJGWH'] => 'CJGWH',
    );
}
