<?php
namespace ResourceCatalog\Model;

interface IUserGroup extends IUserGroupIdentify
{
    const ID = array(
        'NULL' => 0,
        'QFGW' => 1,
        'QWXCB' => 2,
        'AYQZZB' => 3,
        'QWZFW' => 4,
        'QRMFY' => 5,
        'QJCY' => 6,
        'QGAFJ' => 7,
        'QCZJ' => 8,
        'QGXJ' => 9,
        'QJYJ' => 10,
        'QSFJ' => 11,
        'QRSJ' => 12,
        'QZJJ' => 13,
        'QGSL' => 14,
        'QGBDST' => 15,
        'QSLJ' => 16,
        'QLYJ' => 17,
        'QJTYSJ' => 18,
        'AYSTHJJ' => 19,
        'QSAWJ' => 20,
        'QMZJ' => 21,
        'QNYNCJ' => 22,
        'QWGXLJ' => 23,
        'QWJW' => 24,
        'QSUWJ' => 25,
        'QTJJ' => 26,
        'QSCJDGLJ' => 27,
        'QYJGLJ' => 28,
        'QZFJRB' => 29,
        'QZWJ' => 30,
        'QXXZX' => 31,
        'QBWB' => 32,
        'QKJJ' => 33,
        'QSJJ' => 34,
        'QCSGLJ' => 35,
        'QDAJ' => 36,
        'QZGH' => 37,
        'TQW' => 38,
        'ZGRSAYZGS' => 39,
        'QGDFGS' => 40,
        'RBCXAYZGS' => 41,
        'GKZ' => 42,
        'QSZ' => 43,
        'AYZ' => 44,
        'WPZ' => 45,
        'FHJ' => 46,
        'BYIJ' => 47,
        'HBJ' => 48,
        'DDJ' => 49,
        'DJJ' => 50,
        'BYAJ' => 51,
        'CJGWH' => 52,
    );
}
